pub mod error;
pub mod query;
pub mod context;
pub mod discovery;
pub mod optimization;
pub mod storage;
pub mod statguardian;
pub mod mcp;
pub mod executor;
pub mod ml;
pub mod multi_agent;
pub mod decomposition;
pub mod streaming;
pub mod metadata;
pub mod selective_retrieval;
pub mod quality_gates;
pub mod observability;

pub use error::{Error, Result};
pub use query::Query;
pub use context::{Context, ContextType};
pub use discovery::Discovery;
pub use optimization::{OptimizationStrategy, CostMetrics, OptimizationTechnique, StrategyType};
pub use storage::Repository;
pub use statguardian::{ValidationGate, ValidationResult, ValidationStatus};
pub use mcp::{MCPTool, MCPResource, MCPCapabilities};
pub use executor::{QueryExecutor, ExecutionResult, ExecutionStatus};
pub use ml::{LearnedRelevanceModel, TrainingSample, FeedbackType, UserFeedback};
pub use multi_agent::{ContextHub, SharedContext};
pub use decomposition::{QueryDecomposer, DecomposedQuery, QueryStep, ExecutionPlan};
pub use streaming::{ContextStream, StreamedContext};
pub use metadata::{MetadataIntelligence, Metadata, MetadataSource, SourceType};
pub use selective_retrieval::{SelectiveRetrievalEngine, TokenBudget, BudgetTier, QueryIntent};
pub use quality_gates::{QualityGatesEngine, ConfidenceScore, FallbackChain, PolicyEnforcer};
pub use observability::{ObservabilityEngine, DecisionTracer, MetricsCollector, StructuredLogger};
